# Generated by Django 4.0.2 on 2022-02-06 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_contact_email_alter_contact_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='gmail',
        ),
    ]
